### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by PhilMiller1** [aperezdc/webkit2gtk-python-webextension-example#3]
This is all what I get, and a blank page (duckduckgo won't load):

`./run.sh
/home/.../.../.../experiments/extension/browse-with-extension:10: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import WebKit2, Gtk, GLib
Extension directory: /home/.../.../.../experiments/extension
Python loader, extension=0x237ca20
sys:1: PyGIWarning: WebKit2WebExtension was imported without specifying a version first. Use gi.require_version('WebKit2WebExtension', '4.0') before import to ensure that the right version gets loaded.`

**Comment by aperezdc** [comment]
@PhilMiller1: It is a bit confusing that you have closed the issue yourself after reporting it. Did you fix the issue yourself in the end?

**Comment by aperezdc** [comment]
Okay, I can reproduce this myself: it seems like an update to PyGObject made it a bit more picky in regard to the versioning of loaded modules, and some bits of extra code are needed to ensure that PyGObject will be happy to load the `WebKit2WebExtension` module. Reopening.

**Comment by aperezdc** [comment]
This is now fixed, closing.
