### ISSUE TITLE
WebKit2WebExtension.WebExtension::get_page() crash WebView

### ISSUE THREAD

**Issue by ghost** [aperezdc/webkit2gtk-python-webextension-example#6]
Calling this function crash the view.

**Comment by ghost** [comment]
(gdb) backtrace
#0  0x0000000000007f86 in  ()
#1  0x00007f86cc126449 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#2  0x00007f86cc170f6a in _PyFunction_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#3  0x00007f86cc1d934e in _PyObject_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#4  0x00007f86cc1da0b2 in _PyObject_Call_Prepend () at /usr/lib/libpython3.6m.so.1.0
#5  0x00007f86cc1da17b in PyObject_Call () at /usr/lib/libpython3.6m.so.1.0
#6  0x00007f86cc127be3 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#7  0x00007f86cc170f6a in _PyFunction_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#8  0x00007f86cc1d934e in _PyObject_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#9  0x00007f86cc1da0b2 in _PyObject_Call_Prepend () at /usr/lib/libpython3.6m.so.1.0
#10 0x00007f86cc1da17b in PyObject_Call () at /usr/lib/libpython3.6m.so.1.0
#11 0x00007f867f9c283a in  ()
    at /usr/lib/python3.6/site-packages/gi/_gi.cpython-36m-x86_64-linux-gnu.so
#12 0x00007f86e13b2f75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#13 0x00007f86e16b0497 in  () at /usr/lib/libgio-2.0.so.0
#14 0x00007f86e16b17ac in  () at /usr/lib/libgio-2.0.so.0
#15 0x00007f86e10d966a in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#16 0x00007f86e10d9a20 in  () at /usr/lib/libglib-2.0.so.0
#17 0x00007f86e10d9d42 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#18 0x00007f86e0c7d450 in WTF::RunLoop::run() ()
    at /usr/lib/libjavascriptcoregtk-4.0.so.18
#19 0x00007f86e3dd409a in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#20 0x00007f86e3180511 in __libc_start_main () at /usr/lib/libc.so.6
#21 0x000000000040075a in _start ()

**Comment by ghost** [comment]
Ok, my fault :-1:

**Comment by aperezdc** [comment]
@gnumdk: No problem! By the the way, if you think the issue you had here was something that could be a “gotcha“, maybe it can be useful for other people searching for the backtrace if you commented what the issue was and how you fixed it.
